Repository stove-smooth/sgs-smooth, pull requests merged in 2022-01, with the labels that each got.

#51 [feat] 커뮤니티 서버 - 카테고리 관련 API
  src/community-server/src/main/java/com/example/communityserver/controller/CategoryController.java
  src/community-server/src/main/java/com/example/communityserver/controller/CommunityController.java
  src/community-server/src/main/java/com/example/communityserver/domain/Category.java
  src/community-server/src/main/java/com/example/communityserver/domain/CategoryMember.java
  src/community-server/src/main/java/com/example/communityserver/domain/Channel.java
  src/community-server/src/main/java/com/example/communityserver/domain/ChannelMember.java
  src/community-server/src/main/java/com/example/communityserver/domain/Community.java
  src/community-server/src/main/java/com/example/communityserver/domain/CommunityMember.java
  src/community-server/src/main/java/com/example/communityserver/dto/request/CreateCategoryRequest.java
  src/community-server/src/main/java/com/example/communityserver/dto/request/EditCategoryNameRequest.java
  src/community-server/src/main/java/com/example/communityserver/dto/request/InviteCategoryRequest.java
  src/community-server/src/main/java/com/example/communityserver/dto/request/LocateCategoryRequest.java
  src/community-server/src/main/java/com/example/communityserver/exception/CustomExceptionStatus.java
  src/community-server/src/main/java/com/example/communityserver/repository/CategoryRepository.java
  src/community-server/src/main/java/com/example/communityserver/service/CategoryService.java
  src/community-server/src/main/java/com/example/communityserver/service/CommunityService.java
Labels: backend-hd

#62 커뮤니티 서버 dto 수정
  src/community-server/src/main/java/com/example/communityserver/controller/CategoryController.java
  src/community-server/src/main/java/com/example/communityserver/controller/ChannelController.java
  src/community-server/src/main/java/com/example/communityserver/controller/CommunityController.java
  src/community-server/src/main/java/com/example/communityserver/dto/request/CreateChannelRequest.java
  src/community-server/src/main/java/com/example/communityserver/dto/request/CreateInvitationRequest.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/CategoryResponse.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/ChannelDetailResponse.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/ChannelResponse.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/CommunityDetailResponse.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/CommunityResponse.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/CreateCommunityResponse.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/MemberResponse.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/ThreadResponse.java
  src/community-server/src/main/java/com/example/communityserver/exception/ExceptionAdvice.java
  src/community-server/src/main/java/com/example/communityserver/service/ChannelService.java
  src/community-server/src/main/java/com/example/communityserver/service/CommunityService.java
Labels: backend-hd

#64 [feat] friend home view
  src/smooth-ios/smooth-ios.xcodeproj/project.pbxproj
  src/smooth-ios/smooth-ios/Commons/Assets.xcassets/empty-background.imageset/Contents.json
  src/smooth-ios/smooth-ios/Commons/Assets.xcassets/empty-background.imageset/Group@1x.png
  src/smooth-ios/smooth-ios/Commons/Assets.xcassets/empty-background.imageset/Group@2x.png
  src/smooth-ios/smooth-ios/Commons/Assets.xcassets/empty-background.imageset/Group@3x.png
  src/smooth-ios/smooth-ios/Coordinator/MainCoordinator.swift
  src/smooth-ios/smooth-ios/Coordinator/MainTabBarCoordinator.swift
  src/smooth-ios/smooth-ios/Coordinator/TabBar/FriendCoordinator.swift
  src/smooth-ios/smooth-ios/Coordinator/TabBar/HomeCoordinator.swift
  src/smooth-ios/smooth-ios/Model/Friend.swift
  src/smooth-ios/smooth-ios/Model/FriendSection.swift
  src/smooth-ios/smooth-ios/Model/UserInfo.swift
  src/smooth-ios/smooth-ios/Modules/Friend/FriendEmpty/FriendEmptyView.swift
  src/smooth-ios/smooth-ios/Modules/Friend/FriendEmpty/FriendEmptyViewController.swift
  src/smooth-ios/smooth-ios/Modules/Friend/FriendEmpty/FriendEmptyViewModel.swift
  src/smooth-ios/smooth-ios/Modules/Friend/FriendRequest/FriendRequestView.swift
  src/smooth-ios/smooth-ios/Modules/Friend/FriendRequest/FriendRequestViewModel.swift
  src/smooth-ios/smooth-ios/Modules/Friend/FriendTableViewCell.swift
  src/smooth-ios/smooth-ios/Modules/Friend/FriendView.swift
  src/smooth-ios/smooth-ios/Modules/Friend/FriendViewController.swift
  src/smooth-ios/smooth-ios/Modules/Friend/FriendViewModel.swift
  src/smooth-ios/smooth-ios/Modules/Home/Content/ContainerViewController.swift
  src/smooth-ios/smooth-ios/Modules/Home/HomeViewController.swift
  src/smooth-ios/smooth-ios/Modules/Home/Menu/Channel/ChannalCell.swift
  src/smooth-ios/smooth-ios/Modules/Home/Menu/MenuViewController.swift
  src/smooth-ios/smooth-ios/Modules/SignIn/SignInView.swift
  src/smooth-ios/smooth-ios/Modules/SignIn/SignInViewController.swift
  src/smooth-ios/smooth-ios/Modules/SignUp/SignUpInfo/SignUpInfoView.swift
  src/smooth-ios/smooth-ios/Modules/SignUp/SignUpInfo/SignUpInfoViewController.swift
  src/smooth-ios/smooth-ios/Modules/SignUp/SignUpInfo/SignUpInfoViewModel.swift
  src/smooth-ios/smooth-ios/Modules/SignUp/SignUpView.swift
  src/smooth-ios/smooth-ios/Modules/SignUp/SignUpViewController.swift
  src/smooth-ios/smooth-ios/Modules/SignUp/VerifyCodeView.swift
  src/smooth-ios/smooth-ios/Modules/Splash/SplashView.swift
  src/smooth-ios/smooth-ios/Modules/Splash/SplashViewModel.swift
  src/smooth-ios/smooth-ios/Repository/API/FriendAPI.swift
  src/smooth-ios/smooth-ios/Repository/API/UserAPI.swift
  src/smooth-ios/smooth-ios/Repository/FriendRepository.swift
  src/smooth-ios/smooth-ios/Utils/Color+extension.swift
  src/smooth-ios/smooth-ios/Utils/UserDefaultsUtil.swift
Labels: iOS

#65 라우터 구조 변경
  src/sgs-client/package-lock.json
  src/sgs-client/package.json
  src/sgs-client/src/App.vue
  src/sgs-client/src/api/common/interceptors.js
  src/sgs-client/src/api/index.js
  src/sgs-client/src/assets/close-dm.svg
  src/sgs-client/src/assets/trashcan.svg
  src/sgs-client/src/components/CategorySettingModal.vue
  src/sgs-client/src/components/CreateCategoryModal.vue
  src/sgs-client/src/components/CreateChannelModal.vue
  src/sgs-client/src/components/CreateServerModal.vue
  src/sgs-client/src/components/DMListForm.vue
  src/sgs-client/src/components/FriendsNewAdd.vue
  src/sgs-client/src/components/LoginForm.vue
  src/sgs-client/src/components/NavigationBar.vue
  src/sgs-client/src/components/ServerActivityArea.vue
  src/sgs-client/src/components/ServerPopout.vue
  src/sgs-client/src/components/ServerSettingModal.vue
  src/sgs-client/src/components/ServerSideBar.vue
  src/sgs-client/src/components/common/Modal.vue
  src/sgs-client/src/components/common/UserSection.vue
  src/sgs-client/src/css/common.css
  src/sgs-client/src/main.js
  src/sgs-client/src/pages/LoginPage.vue
  src/sgs-client/src/pages/MainPage.vue
  src/sgs-client/src/pages/Mypage.vue
  src/sgs-client/src/pages/NotFoundPage.vue
  src/sgs-client/src/pages/ServerPage.vue
  src/sgs-client/src/pages/ServerWelcomePage.vue
  src/sgs-client/src/pages/UserSettingPage.vue
  src/sgs-client/src/routes/guard.js
  src/sgs-client/src/routes/index.js
  src/sgs-client/src/store/module/friends.js
  src/sgs-client/src/store/module/server.js
  src/sgs-client/src/store/module/user.js
  src/sgs-client/src/store/module/utils.js
  src/sgs-client/src/utils/common.js
Labels: web

#70 [fix] 커뮤니티, 채널 배치 순서 변경 에러 수정
  src/community-server/build.gradle
  src/community-server/src/main/java/com/example/communityserver/controller/CommunityController.java
  src/community-server/src/main/java/com/example/communityserver/domain/Category.java
  src/community-server/src/main/java/com/example/communityserver/domain/Channel.java
  src/community-server/src/main/java/com/example/communityserver/domain/CommunityMember.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/CategoryResponse.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/ChannelDetailResponse.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/CommunityDetailResponse.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/MemberListFeignResponse.java
  src/community-server/src/main/java/com/example/communityserver/service/CategoryService.java
  src/community-server/src/main/java/com/example/communityserver/service/ChannelService.java
  src/community-server/src/main/java/com/example/communityserver/service/CommunityService.java
  src/signaling-server/.gitignore
  src/signaling-server/build.gradle
  src/signaling-server/gradle/wrapper/gradle-wrapper.jar
  src/signaling-server/gradle/wrapper/gradle-wrapper.properties
  src/signaling-server/gradlew
  src/signaling-server/gradlew.bat
  src/signaling-server/settings.gradle
  src/signaling-server/src/main/java/com/example/signalingserver/SignalingServerApplication.java
  src/signaling-server/src/main/java/com/example/signalingserver/config/FilterChannelInterceptor.java
  src/signaling-server/src/main/java/com/example/signalingserver/config/JwtTokenFilter.java
  src/signaling-server/src/main/java/com/example/signalingserver/config/KurentoConfig.java
  src/signaling-server/src/main/java/com/example/signalingserver/config/RedisConfig.java
  src/signaling-server/src/test/java/com/example/signalingserver/SignalingServerApplicationTests.java
Labels: backend-hd

#73 [feat] 커뮤니티 서버 - 채팅방 API
  src/community-server/src/main/java/com/example/communityserver/client/UserClient.java
  src/community-server/src/main/java/com/example/communityserver/controller/CommunityController.java
  src/community-server/src/main/java/com/example/communityserver/controller/RoomController.java
  src/community-server/src/main/java/com/example/communityserver/domain/Room.java
  src/community-server/src/main/java/com/example/communityserver/domain/RoomInvitation.java
  src/community-server/src/main/java/com/example/communityserver/domain/RoomMember.java
  src/community-server/src/main/java/com/example/communityserver/dto/request/CreateRoomRequest.java
  src/community-server/src/main/java/com/example/communityserver/dto/request/EditIconRequest.java
  src/community-server/src/main/java/com/example/communityserver/dto/request/JoinRequest.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/RoomDetailResponse.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/RoomListResponse.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/RoomMemberResponse.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/RoomResponse.java
  src/community-server/src/main/java/com/example/communityserver/exception/CustomExceptionStatus.java
  src/community-server/src/main/java/com/example/communityserver/repository/RoomInvitationRepository.java
  src/community-server/src/main/java/com/example/communityserver/repository/RoomMemberRepository.java
  src/community-server/src/main/java/com/example/communityserver/repository/RoomRepository.java
  src/community-server/src/main/java/com/example/communityserver/service/CategoryService.java
  src/community-server/src/main/java/com/example/communityserver/service/CommunityService.java
  src/community-server/src/main/java/com/example/communityserver/service/RoomService.java
Labels: backend-hd

#75 [fix] 기존 방관리 서비스 삭제
  src/community-server/src/main/java/com/example/communityserver/controller/RoomController.java
  src/room-server/.gitignore
  src/room-server/build.gradle
  src/room-server/gradle/wrapper/gradle-wrapper.jar
  src/room-server/gradle/wrapper/gradle-wrapper.properties
  src/room-server/gradlew
  src/room-server/gradlew.bat
  src/room-server/settings.gradle
  src/room-server/src/main/java/com/example/roomserver/RoomServerApplication.java
  src/room-server/src/main/java/com/example/roomserver/client/AccountClient.java
  src/room-server/src/main/java/com/example/roomserver/controller/RoomController.java
  src/room-server/src/main/java/com/example/roomserver/domain/AccountRoom.java
  src/room-server/src/main/java/com/example/roomserver/domain/BaseTimeEntity.java
  src/room-server/src/main/java/com/example/roomserver/domain/Room.java
  src/room-server/src/main/java/com/example/roomserver/dto/response/AccountInfoResponse.java
  src/room-server/src/main/java/com/example/roomserver/dto/response/CommonResponse.java
  src/room-server/src/main/java/com/example/roomserver/dto/response/DataResponse.java
  src/room-server/src/main/java/com/example/roomserver/dto/response/RoomListResponse.java
  src/room-server/src/main/java/com/example/roomserver/exception/CustomException.java
  src/room-server/src/main/java/com/example/roomserver/exception/CustomExceptionStatus.java
  src/room-server/src/main/java/com/example/roomserver/exception/ExceptionAdvice.java
  src/room-server/src/main/java/com/example/roomserver/repository/AccountRoomRepository.java
  src/room-server/src/main/java/com/example/roomserver/repository/RoomRepository.java
  src/room-server/src/main/java/com/example/roomserver/service/ResponseService.java
  src/room-server/src/main/java/com/example/roomserver/service/RoomService.java
  src/room-server/src/test/java/com/example/roomserver/RoomServerApplicationTests.java
Labels: backend-hd

#77 [feat] 시그널링 서버 커넥션 및 세션 관리
  src/community-server/src/main/java/com/example/communityserver/controller/ChannelController.java
  src/community-server/src/main/java/com/example/communityserver/domain/Channel.java
  src/community-server/src/main/java/com/example/communityserver/dto/request/LocateChannelRequest.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/ChannelResponse.java
  src/community-server/src/main/java/com/example/communityserver/service/ChannelService.java
  src/community-server/src/main/java/com/example/communityserver/service/CommunityService.java
  src/signaling-server/src/main/java/com/example/signalingserver/config/FilterChannelInterceptor.java
  src/signaling-server/src/main/java/com/example/signalingserver/config/JwtFilter.java
  src/signaling-server/src/main/java/com/example/signalingserver/config/MessageHandler.java
  src/signaling-server/src/main/java/com/example/signalingserver/config/WebSocketConfig.java
  src/signaling-server/src/main/java/com/example/signalingserver/controller/DemoController.java
  src/signaling-server/src/main/java/com/example/signalingserver/domain/Room.java
  src/signaling-server/src/main/java/com/example/signalingserver/domain/UserSession.java
  src/signaling-server/src/main/java/com/example/signalingserver/dto/request/CandidateRequest.java
  src/signaling-server/src/main/java/com/example/signalingserver/dto/request/JoinRequest.java
  src/signaling-server/src/main/java/com/example/signalingserver/dto/request/ReceiveVideoRequest.java
  src/signaling-server/src/main/java/com/example/signalingserver/util/RoomManager.java
  src/signaling-server/src/main/java/com/example/signalingserver/util/UserRegister.java
  src/signaling-server/src/main/java/com/example/signalingserver/util/type/Message.java
  src/signaling-server/src/main/java/com/example/signalingserver/util/type/Property.java
  src/signaling-server/src/main/resources/static/css/style.css
  src/signaling-server/src/main/resources/static/js/conferenceroom-smooth.js
  src/signaling-server/src/main/resources/static/js/kurento-util-smooth.js
  src/signaling-server/src/main/resources/static/js/participant.js
  src/signaling-server/src/main/resources/static/js/sockjs-client.js
  src/signaling-server/src/main/resources/templates/home.html
Labels: backend-hd

#83 Feature/hd
  src/community-server/build.gradle
  src/community-server/src/main/java/com/example/communityserver/config/RedisConfig.java
  src/community-server/src/main/java/com/example/communityserver/controller/ChannelController.java
  src/community-server/src/main/java/com/example/communityserver/controller/RoomController.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/AddressResponse.java
  src/community-server/src/main/java/com/example/communityserver/service/ChannelService.java
  src/community-server/src/main/java/com/example/communityserver/service/RoomService.java
  src/signaling-server/src/main/java/com/example/signalingserver/SignalingServerApplication.java
  src/signaling-server/src/main/java/com/example/signalingserver/config/MessageHandler.java
  src/signaling-server/src/main/java/com/example/signalingserver/controller/DemoController.java
  src/signaling-server/src/main/java/com/example/signalingserver/domain/UserSession.java
  src/signaling-server/src/main/resources/static/js/getScreenId.js
  src/signaling-server/src/main/resources/static/js/kurento-util-smooth.js
  src/signaling-server/src/main/resources/templates/home.html
Labels: backend-hd

#84 Server
  src/community-server/build.gradle
  src/community-server/src/main/java/com/example/communityserver/config/RedisConfig.java
  src/community-server/src/main/java/com/example/communityserver/controller/ChannelController.java
  src/community-server/src/main/java/com/example/communityserver/controller/RoomController.java
  src/community-server/src/main/java/com/example/communityserver/domain/Channel.java
  src/community-server/src/main/java/com/example/communityserver/dto/request/LocateChannelRequest.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/AddressResponse.java
  src/community-server/src/main/java/com/example/communityserver/dto/response/ChannelResponse.java
  src/community-server/src/main/java/com/example/communityserver/service/ChannelService.java
  src/community-server/src/main/java/com/example/communityserver/service/CommunityService.java
  src/community-server/src/main/java/com/example/communityserver/service/RoomService.java
  src/signaling-server/src/main/java/com/example/signalingserver/SignalingServerApplication.java
  src/signaling-server/src/main/java/com/example/signalingserver/config/FilterChannelInterceptor.java
  src/signaling-server/src/main/java/com/example/signalingserver/config/JwtFilter.java
  src/signaling-server/src/main/java/com/example/signalingserver/config/MessageHandler.java
  src/signaling-server/src/main/java/com/example/signalingserver/config/WebSocketConfig.java
  src/signaling-server/src/main/java/com/example/signalingserver/controller/DemoController.java
  src/signaling-server/src/main/java/com/example/signalingserver/domain/Room.java
  src/signaling-server/src/main/java/com/example/signalingserver/domain/UserSession.java
  src/signaling-server/src/main/java/com/example/signalingserver/dto/request/CandidateRequest.java
  src/signaling-server/src/main/java/com/example/signalingserver/dto/request/JoinRequest.java
  src/signaling-server/src/main/java/com/example/signalingserver/dto/request/ReceiveVideoRequest.java
  src/signaling-server/src/main/java/com/example/signalingserver/util/RoomManager.java
  src/signaling-server/src/main/java/com/example/signalingserver/util/UserRegister.java
  src/signaling-server/src/main/java/com/example/signalingserver/util/type/Message.java
  src/signaling-server/src/main/java/com/example/signalingserver/util/type/Property.java
  src/signaling-server/src/main/resources/static/css/style.css
  src/signaling-server/src/main/resources/static/js/conferenceroom-smooth.js
  src/signaling-server/src/main/resources/static/js/getScreenId.js
  src/signaling-server/src/main/resources/static/js/kurento-util-smooth.js
  src/signaling-server/src/main/resources/static/js/participant.js
  src/signaling-server/src/main/resources/static/js/sockjs-client.js
  src/signaling-server/src/main/resources/templates/home.html
Labels: backend-hd

#86 커뮤니티(서버) 기본기능
  src/smooth-ios/Podfile
  src/smooth-ios/smooth-ios.xcodeproj/project.pbxproj
  src/smooth-ios/smooth-ios.xcodeproj/xcuserdata/duri.xcuserdatad/xcschemes/xcschememanagement.plist
  src/smooth-ios/smooth-ios/Base/BaseResponse.swift
  src/smooth-ios/smooth-ios/Commons/AppDelegate.swift
  src/smooth-ios/smooth-ios/Commons/Assets.xcassets/Image+Upload.imageset/Contents.json
  src/smooth-ios/smooth-ios/Commons/Assets.xcassets/Image+Upload.imageset/Group@1x.png
  src/smooth-ios/smooth-ios/Commons/Assets.xcassets/Image+Upload.imageset/Group@2x.png
  src/smooth-ios/smooth-ios/Commons/Assets.xcassets/Image+Upload.imageset/Group@3x.png
  src/smooth-ios/smooth-ios/Coordinator/MainTabBarCoordinator.swift
  src/smooth-ios/smooth-ios/Coordinator/TabBar/HomeCoordinator.swift
  src/smooth-ios/smooth-ios/Model/Community.swift
  src/smooth-ios/smooth-ios/Model/Member.swift
  src/smooth-ios/smooth-ios/Modules/AddServer/Join/JoinServerViewController.swift
  src/smooth-ios/smooth-ios/Modules/AddServer/Join/JoinServerViewModel.swift
  src/smooth-ios/smooth-ios/Modules/Home/Channel-make/MakeChannelView.swift
  src/smooth-ios/smooth-ios/Modules/Home/Channel-make/MakeChannelViewController.swift
  src/smooth-ios/smooth-ios/Modules/Home/Menu/MenuView.swift
  src/smooth-ios/smooth-ios/Modules/Home/Menu/MenuViewController.swift
  src/smooth-ios/smooth-ios/Modules/Home/Menu/MenuViewModel.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-Info/EditProfile/EditServerInfoView.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-Info/EditProfile/EditServerInfoViewController.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-Info/EditProfile/EditServerInfoViewModel.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-Info/ServerInfoView.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-Info/ServerInfoViewController.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-Info/ServerInfoViewModel.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-Info/SubView/ServerInfoCell.swift
  src/smooth-ios/smooth-ios/Modules/Home/SubView/ChannalCell.swift
  src/smooth-ios/smooth-ios/Modules/Home/SubView/ChannelView.swift
  src/smooth-ios/smooth-ios/Modules/Home/SubView/ServerCell.swift
  src/smooth-ios/smooth-ios/Repository/API/ServerAPI.swift
  src/smooth-ios/smooth-ios/Repository/ServerRepository.swift
  src/smooth-ios/smooth-ios/Utils/AlertUtils.swift
Labels: iOS

#90 초대장 기본
  src/smooth-ios/smooth-ios.xcodeproj/project.pbxproj
  src/smooth-ios/smooth-ios/Commons/Assets.xcassets/empty-list.imageset/Contents.json
  src/smooth-ios/smooth-ios/Commons/Assets.xcassets/empty-list.imageset/Group@1x.png
  src/smooth-ios/smooth-ios/Commons/Assets.xcassets/empty-list.imageset/Group@2x.png
  src/smooth-ios/smooth-ios/Commons/Assets.xcassets/empty-list.imageset/Group@3x.png
  src/smooth-ios/smooth-ios/Coordinator/MainCoordinator.swift
  src/smooth-ios/smooth-ios/Coordinator/TabBar/AddServerCoordinator.swift
  src/smooth-ios/smooth-ios/Coordinator/TabBar/HomeCoordinator.swift
  src/smooth-ios/smooth-ios/Coordinator/TabBar/ServerSettingCoordinator.swift
  src/smooth-ios/smooth-ios/Model/Invitation.swift
  src/smooth-ios/smooth-ios/Modules/AddServer/AddServerView.swift
  src/smooth-ios/smooth-ios/Modules/Home/Channel-make/MakeChannelView.swift
  src/smooth-ios/smooth-ios/Modules/Home/Channel-make/MakeChannelViewController.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-Info/ServerInfoCell.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-Info/ServerInfoView.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-Info/ServerInfoViewController.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-setting/Server-Invite/ServerInviteListView.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-setting/Server-Invite/ServerInviteListViewController.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-setting/Server-Invite/ServerInviteListViewModel.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-setting/Server-edit/EditServerInfoView.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-setting/Server-edit/EditServerInfoViewController.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-setting/Server-edit/EditServerInfoViewModel.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-setting/ServerSettingView.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-setting/ServerSettingViewController.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-setting/ServerSettingViewModel.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-setting/SubView/ServerInviteCell.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-setting/SubView/ServerInviteEmptyView.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-setting/SubView/ServerSettingCell.swift
  src/smooth-ios/smooth-ios/Modules/Home/Server-setting/SubView/ServerSettingHeaderCell.swift
  src/smooth-ios/smooth-ios/Repository/API/ServerAPI.swift
  src/smooth-ios/smooth-ios/Repository/ServerRepository.swift
  src/smooth-ios/smooth-ios/Utils/Extension/Color+extension.swift
Labels: iOS

#91 커뮤니티 설정 관련 UI
  src/sgs-client/src/components/CategorySettingModal.vue
  src/sgs-client/src/components/ChannelSettingModal.vue
  src/sgs-client/src/components/DMActivityArea.vue
  src/sgs-client/src/components/DeleteMessageModal.vue
  src/sgs-client/src/components/FriendsNowPlayingList.vue
  src/sgs-client/src/components/FriendsProfileModal.vue
  src/sgs-client/src/components/MessagePlusAction.vue
  src/sgs-client/src/components/ServerActivityArea.vue
  src/sgs-client/src/components/ServerSettingModal.vue
  src/sgs-client/src/css/common.css
  src/sgs-client/src/pages/UserSettingPage.vue
Labels: web
